In [1]:
import numpy as np

In [2]:
linear_data = np.arange(0, 10)
print("Лінійні дані:", linear_data)

Лінійні дані: [0 1 2 3 4 5 6 7 8 9]


In [3]:
random_data = np.random.rand(10)
print("Випадкові дані:", random_data)

Випадкові дані: [0.0154649  0.1897193  0.93035385 0.45201954 0.22850672 0.40817322
 0.52351168 0.15901615 0.63771571 0.62816609]


In [4]:
print("Перший елемент (linear):", linear_data[0])
print("Останній елемент (random):", random_data[-1])

Перший елемент (linear): 0
Останній елемент (random): 0.6281660874263622


In [5]:
linear_data[2] = 99
print("Після оновлення:", linear_data)

Після оновлення: [ 0  1 99  3  4  5  6  7  8  9]


In [6]:
random_data_deleted = np.delete(random_data, 4)
print("Після видалення елемента:", random_data_deleted)

Після видалення елемента: [0.0154649  0.1897193  0.93035385 0.45201954 0.40817322 0.52351168
 0.15901615 0.63771571 0.62816609]


In [7]:
linear_data

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

In [8]:
random_data

array([0.0154649 , 0.1897193 , 0.93035385, 0.45201954, 0.22850672,
       0.40817322, 0.52351168, 0.15901615, 0.63771571, 0.62816609])

In [9]:
random_data_deleted

array([0.0154649 , 0.1897193 , 0.93035385, 0.45201954, 0.40817322,
       0.52351168, 0.15901615, 0.63771571, 0.62816609])