In [1]:
import numpy as np


In [2]:
scalar = np.array(7)
print("Scalar:", scalar)

vector = np.arange(10)
print("Vector:", vector)

np.random.seed(0)  
matrix = np.random.rand(4, 5)
print("Matrix:\n", matrix)


Scalar: 7
Vector: [0 1 2 3 4 5 6 7 8 9]
Matrix:
 [[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]]


In [3]:
print("Scalar value:", scalar.item())
print("First element vector[0]:", vector[0])
print("Slice vector[2:6]:", vector[2:6])
print("Even elements:", vector[vector % 2 == 0])

print("Matrix element [1,2]:", matrix[1,2])
print("Matrix row 1:", matrix[1])
print("Matrix column 2:", matrix[:,2])
print("Submatrix rows 1..2, cols 2..4:\n", matrix[1:3, 2:5])


Scalar value: 7
First element vector[0]: 0
Slice vector[2:6]: [2 3 4 5]
Even elements: [0 2 4 6 8]
Matrix element [1,2]: 0.8917730007820798
Matrix row 1: [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
Matrix column 2: [0.60276338 0.891773   0.56804456 0.83261985]
Submatrix rows 1..2, cols 2..4:
 [[0.891773   0.96366276 0.38344152]
 [0.56804456 0.92559664 0.07103606]]


In [4]:
scalar[...] = 42
print("Updated scalar:", scalar)

vector[3] = 99
print("Vector after update:", vector)

vector[vector % 2 == 1] = -1
print("Vector after replacing odd values:", vector)

matrix[0,0] = -0.5
print("Matrix after update:\n", matrix)

col0 = matrix[:,0]
matrix[:,0] = (col0 - col0.mean()) / col0.std()
print("Matrix after normalizing column 0:\n", matrix)


Updated scalar: 42
Vector after update: [ 0  1  2 99  4  5  6  7  8  9]
Vector after replacing odd values: [ 0 -1  2 -1  4 -1  6 -1  8 -1]
Matrix after update:
 [[-0.5         0.71518937  0.60276338  0.54488318  0.4236548 ]
 [ 0.64589411  0.43758721  0.891773    0.96366276  0.38344152]
 [ 0.79172504  0.52889492  0.56804456  0.92559664  0.07103606]
 [ 0.0871293   0.0202184   0.83261985  0.77815675  0.87001215]]
Matrix after normalizing column 0:
 [[-1.4836671   0.71518937  0.60276338  0.54488318  0.4236548 ]
 [ 0.76461955  0.43758721  0.891773    0.96366276  0.38344152]
 [ 1.05074523  0.52889492  0.56804456  0.92559664  0.07103606]
 [-0.33169768  0.0202184   0.83261985  0.77815675  0.87001215]]


In [5]:
scalar = scalar.astype(float)
scalar[...] = np.nan
print("Deleted scalar (set NaN):", scalar)

vector2 = np.delete(vector, 3)
print("Vector after delete:", vector2)

matrix_row_removed = np.delete(matrix, 2, axis=0)
matrix_col_removed = np.delete(matrix, 1, axis=1)

print("Matrix with row 2 removed:\n", matrix_row_removed)
print("Matrix with column 1 removed:\n", matrix_col_removed)


Deleted scalar (set NaN): nan
Vector after delete: [ 0 -1  2  4 -1  6 -1  8 -1]
Matrix with row 2 removed:
 [[-1.4836671   0.71518937  0.60276338  0.54488318  0.4236548 ]
 [ 0.76461955  0.43758721  0.891773    0.96366276  0.38344152]
 [-0.33169768  0.0202184   0.83261985  0.77815675  0.87001215]]
Matrix with column 1 removed:
 [[-1.4836671   0.60276338  0.54488318  0.4236548 ]
 [ 0.76461955  0.891773    0.96366276  0.38344152]
 [ 1.05074523  0.56804456  0.92559664  0.07103606]
 [-0.33169768  0.83261985  0.77815675  0.87001215]]
